name: Build Test

# Manually trigger the action with a button in GitHub
# Alternatively, trigger on release / push etc.
on:
  push:
  workflow_dispatch:

jobs:
  test-full:
    name: Test on Nextflow Tower
    # Don't try to run on forked repos
    # run when commit message contains [test]
    if: github.repository == 'wslh-bio/SPNtypeID' && contains(github.event.head_commit.message, '[test]')
    runs-on: ubuntu-latest
    steps:
      - uses: k-florek/tower-action@main
        # Use repository secrets for sensitive fields
        with:
          workspace_id: ${{ secrets.TOWER_WORKSPACE_ID }}
          access_token: ${{ secrets.NEXTFLOW_TOWER_ACCESS_TOKEN }}
          compute_env: ${{ secrets.TOWER_COMPUTE_ENV }}
          run_name: ${{ github.job }}_${{ github.run_attempt }}
          workdir: ${{ secrets.AWS_S3_BUCKET }}/work/${{ github.sha }}
          # Set any custom pipeline params here - JSON object as a string
          parameters: |
            {
                "outdir": "${{ secrets.AWS_S3_BUCKET }}/results/${{ github.sha }}"
            }
          # List of pipeline config profiles to use - comma separated list as a string
          profiles: test_full,aws_tower
      - uses: actions/upload-artifact@v3
        with:
          name: Tower debug log file
          path: tower_action_*.log